### ISSUE TITLE
tinydrm_display_pipe_prepare_fb  missing

### ISSUE THREAD

**Issue by sergey-suloev** [notro/tinydrm#11]
@notro 
hi, where is tinydrm_display_pipe_prepare_fb   in v4.18 ?  Should we use  "drm_gem_fb_simple_display_pipe_prepare_fb"  instead ?

**Comment by dlech** [comment]
Yes, that is what replaced it.

https://github.com/torvalds/linux/commit/ccc3b2b3482c2c05d05fd2cfbf0c28d644b4b0c2#diff-6c583c0659631a4eff61d6c48c2b3169

**Comment by sergey-suloev** [comment]
@dlech 
thx
