### ISSUE TITLE
Trouble transitioning an ILI9341 from fbtft to tinydrm

### ISSUE THREAD

**Issue by lephe** [notro/tinydrm#14]
First of all, thanks for your hard work on these drivers. :grin: 

I'm working with [EastRising's ILI9341-based ER-TFTM024-3](https://www.buydisplay.com/default/qvga-2-4-inch-tft-lcd-touch-shield-320x240-serial-module-display-ili9341) wired through the 4-wire SPI Interface II to a Raspberry Pi Zero.

The problem, bluntly, is that loading `fb_ili9341` produces a usable framebuffer in `/dev/fb1`, but the tinydrm-based `ili9341` seems unable to communicate with the display. The screen remains blank.

After enabling full debugging in the `drm` module, I found out that **everything read from the display is 0**. Essentially, everything in `/sys/kernel/debug/dri/0/command` (and the output of the `mipi-dcs` debugging tool) is just a bunch of zeros.

I don't have much more clues, unfortunately. `modetest -M ili9341` returns the usual set of relevant information, but no test image ever gets to the display. Although there is some communication since lowering the SPI bus frequency clearly slows down the test.

Here is my device tree, if it might help : [display.txt](https://github.com/notro/tinydrm/files/2804427/display.txt).

Any insight or clue is most welcome. :smiley:

**Comment by dlech** [comment]
What linux kernel are you using?

**Comment by lephe** [comment]
So fast, thanks!

That would be `4.19.12-raspberrypi+`. It's a custom build for `armv6l`.

**Comment by notro** [comment]
> The screen remains blank.

Blank as in backlight on all pixels black?

**Comment by lephe** [comment]
> Blank as in backlight on all pixels black?

Rather blank as in backlight on all pixels white:

![blank](https://user-images.githubusercontent.com/33732078/51863554-a20b3280-2341-11e9-856b-fb84d61b9c16.png)

If I load `fb_ili9341`, the contents of the framebuffer (black by default) are sent to the display and it produces a huge, unmistakable difference.

**Comment by notro** [comment]
That's an uninitialized controller.

I think I see the problem, you have this:
```
compatible = "adafruit,yx240qv29", "ilitek,ili9341";
```
You probably have a pitft28 (mi0283qt panel) compatible display. For that you need the mi0283qt driver.
```
compatible = "mi,mi0283qt";
```
Example overlay: https://github.com/notro/tinydrm/blob/master/rpi-overlays/rpi-display-overlay.dts

**Comment by lephe** [comment]
> That's an uninitialized controller.

I was suspecting this, but now it's clear, thanks!

> You probably have a pitft28 (mi0283qt panel) compatible display. For that you need the mi0283qt driver.

I bumped across that in the documentation earlier. I just tested it with my device tree and -unfortunately- having `mi0283qt` loaded instead of `ili9341` makes no visible difference.

Everything I observed earlier still holds (except for running `modetest` with `-M mi0283qt` of course).

I will test with standard device trees but apart from renumbering pins and forgetting the touch screen there should be few differences. Are there any other ILI9341-based boards to try out, just in case? ^^

**Comment by lephe** [comment]
It turns out that I was wrong as the example device tree overlay over there works better than mine: it does not initialize the controller at startup when the `mi0283qt` module is loaded, but at least running `modetest` will initialize the controller and successfully display the test image. When that happens, the framebuffer starts working.

More interesting now, running `mipi-dcs` will turn back the controller to its unitialized state! I can't say I understand what's going on under-the-hood.

Anyway, my hours of testing must not have been thorough. This is helping me a lot. :smiley:

**Comment by notro** [comment]
> it does not initialize the controller at startup

That is correct and differs from fbtft. DRM drivers initialize when the display pipeline is enabled. This happens from userspace, either DRM or fbdev (or fbcon).

**Comment by lephe** [comment]
> That is correct and differs from fbtft. DRM drivers initialize when the display pipeline is enabled. This happens from userspace, either DRM or fbdev (or fbcon).

So far so good then! :blush:

I've looked up how to make this the primary display: ideally light it up at bootup and get a console, much like the VGA screen I'm working on for now.

Does this require using the graphics card with PRIME? Maybe use a builtin kernel module? I think I've seen this mentioned in the wiki, but there's not a lot of details.

**Comment by notro** [comment]
If you want the driver loaded as early as possible, it needs to be builtin.
If this is the only grahichs device, fbcon will attach to it. If you have more graphic devices, you may need to instruct fbcon which device to attach to: https://github.com/notro/fbtft/wiki/Boot-console#enable-console

PRIME is only needed for accelerated rendering.
