### ISSUE TITLE
Do the DRM drivers support rotation?

### ISSUE THREAD

**Issue by yam001** [notro/tinydrm#26]
Both ili9341 and ili9486 drivers do not rotate the screens, rotation works great under fbtft. What needs to be changed in the code to support this? Is there an example implementation?

**Comment by notro** [comment]
Both drivers support the 'rotation' Device Tree property.
Example: https://elixir.bootlin.com/linux/v5.10/source/drivers/gpu/drm/tiny/ili9341.c#L210

**Comment by yam001** [comment]
Thanks for your help, its working perfect. I did not notice I should use rotation instead of rotate as for fbtft.

**Comment by yam001** [comment]
Thank you.
