### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by Ivoah** [notro/tinydrm#4]
Consider adding a README.md so new people can see what the project is and how it differs from fbtft.

**Comment by notro** [comment]
I have written a couple of words.

**Comment by jamesdownsbell** [comment]
Hi, notro 
              I haven't picked up a pi for awhile, but I'm pleased to see fbtft has come this far. Well done dude I know you've worked on this. Can't wait to try this new project 👍🏼

**Comment by notro** [comment]
Thanks, it's been a long hill to climb.
