### ISSUE TITLE
tinydrm_lastclose

### ISSUE THREAD

**Issue by sergey-suloev** [notro/tinydrm#8]
Hi, what is the substitution for tinydrm_lastclose ?

**Comment by notro** [comment]
I don't understand the question, can you elaborate.

**Comment by sergey-suloev** [comment]
"tinydrm_lastclose" is a function that is missing in latest kernel. what should be used instead ?

**Comment by notro** [comment]
Oh sorry I forgot about that change: drm_fb_helper_lastclose should be used.

**Comment by sergey-suloev** [comment]
thx for quick response!

do you have some release info what has been added/changed in 4.16 ?

**Comment by notro** [comment]
Major changes are reported here: https://github.com/notro/tinydrm/issues/2

Commit log up to and including 4.16: https://github.com/torvalds/linux/commits/master/drivers/gpu/drm/tinydrm
Commit log for 4.17: https://cgit.freedesktop.org/drm/drm-misc/log/drivers/gpu/drm/tinydrm
tinydrm patches are committed to drm-misc.
